### ISSUE TITLE
Repo not linked from packrat-lite blog post

### ISSUE THREAD

**Issue by RaoOfPhysics** [MilesMcBain/packrat_demo#2]
Hi @MilesMcBain! Thanks for writing [this nice blog post about packrat](https://milesmcbain.xyz/packrat-lite/). I noticed however that this repo isn't linked from the post. The HTML says:

```html
… I used to create <a href="">this example repo</a>…
```

rather than:

```html
… I used to create <a href="https://github.com/MilesMcBain/packrat_demo/">this example repo</a>…
```

Cheers,
A.

**Comment by MilesMcBain** [comment]
Whoops! Thanks very much @RaoOfPhysics. :+1:
